# Generated by Django 4.2.1 on 2023-06-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishing_house',
        ),
    ]
