# Generated by Django 4.2.1 on 2023-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_book_cover_remove_book_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.AddField(
            model_name='cart',
            name='book_format',
            field=models.CharField(choices=[('audio', 'Audio'), ('physical', 'Physical')], default='physical', max_length=10),
        ),
    ]
