# Generated by Django 4.2.1 on 2023-06-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.deliveryinfo'),
        ),
    ]
